mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
	url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^AddTask/$', views.AddTask, name='AddTask'),
    url(r'^ListOnDueDate/$', views.ListOnDueDate, name='ListOnDueDate'),
    url(r'^CrossedDates/$', views.CrossedDates, name='CrossedDates'),
    url(r'^ListOnDay/$', views.ListOnDay, name='ListOnDay'),
    url(r'^ListOnWeek/$', views.ListOnWeek, name='ListOnWeek'),
    url(r'^ListOnYear/$', views.ListOnYear, name='ListOnYear'),
    url(r'^ListOnMonth/$', views.ListOnMonth, name='ListOnMonth'),
    url(r'^EditStatus/(?P<pk>\d+)/$', views.EditStatus, name='EditStatus'),
    url(r'^(?P<id>[0-9]+)/$', views.TaskInfo, name='TaskInfo')
    
]

polls/models.py
from django.db import models
from django.utils import timezone
from datetime import date


# Create your models here.

PRIORITY_CHOICES = ( 

  (1, 'ONE (LOW)'), 

  (2, 'TWO'), 

  (3, 'THREE (NORMAL)'), 
  
  (4, 'FOUR'), 

  (5, 'FIVE (HIGH)'), 

) 

STATUS_CHOICES = ( 

  (1, 'To do'), 

  (2, 'Doing'), 

  (3, 'Done'), 

) 



class Tasks(models.Model):
    task_name=models.CharField(max_length=200)
    task_createDate=models.DateTimeField(timezone.now())
    task_desc=models.CharField(max_length=200)
    task_status=models.IntegerField(choices=STATUS_CHOICES, default=1)
    task_priority=models.IntegerField(choices=PRIORITY_CHOICES, default=3)
    task_Due=models.DateField()
    

@property
def is_past_due(self):
    if date.today() > self.date:
        return True
    return False



#class TaskDetails(models.Model):
#tasks=models.ForeignKey(Tasks, on_delete=models.CASCADE)
#task_desc=models.CharField(max_length=200)
#task_status=models.CharField(max_length=200)
#task_priority=models.IntegerField(default=3)
#task_Due=models.DateField()
    

    

polls/forms.py
from django import forms
from .models import Tasks
#from .models import TaskDetails

class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = ('task_name', 'task_desc','task_priority', 'task_status','task_Due',)
      
class EditTaskStatus(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = ('task_status',)

polls/views.py
from django.shortcuts import render
from django.shortcuts import loader
from django.http import Http404
from django.utils import timezone
from datetime import date
from datetime import datetime
import datetime

# Create your views here.
from django.http import HttpResponse
from django.shortcuts import redirect
from .models import Tasks
#from .models import TaskDetails
from .forms import AddTaskForm
from .forms import EditTaskStatus

from django.shortcuts import get_object_or_404

def index(request):
    task_list=Tasks.objects.order_by('-task_createDate')[:50]
    template=loader.get_template('polls/index.html')
    context={'task_list':task_list,}
    return HttpResponse(template.render(context,request))

def TaskInfo(request,id):
    try:
        task = Tasks.objects.get(pk=id)
        #task1 = TaskDetails.objects.get(pk=id)
    except Tasks.DoesNotExist:
        raise Http404("Task does not exist")
    #return render(request, 'polls/TaskInfo.html', {'task': task, 'task1': task1})
    return render(request, 'polls/TaskInfo.html', {'task': task})
    
def AddTask(request):
    #template=loader.get_template('polls/AddTask.html')
    #return HttpResponse(template.render(request))
    if request.method == "POST":
        form = AddTaskForm(request.POST)
        if form.is_valid():
            TasksAdded = form.save(commit=False)
            TasksAdded.task_createDate = timezone.now()
            TasksAdded.save()
            task = Tasks.objects.get(pk=TasksAdded.id)
            return render(request, 'polls/TaskInfo.html', {'task': task})
            #return redirect('TaskInfo', pk=Tasks.id)
    
    else:
        form = AddTaskForm()
    return render(request, 'polls/AddTask.html', {'form': form})
    
def EditStatus(request,pk):
    
    
    post = get_object_or_404(Tasks, pk=pk)
    if request.method == "POST":
        form = EditTaskStatus(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            task = Tasks.objects.get(pk=post.id)
            return render(request, 'polls/TaskInfo.html', {'task': task})
            #return redirect('TaskInfo', pk=post.pk)
    else:
        form = EditTaskStatus(instance=post)
    return render(request, 'polls/EditStatus.html', {'form': form})
    

    
    
def ListOnDueDate(request):
    task_list=Tasks.objects.order_by('-task_Due')[:50]
    template=loader.get_template('polls/ListOnDueDate.html')
    today =date.today()
    context={'task_list':task_list,'today':today}
    return HttpResponse(template.render(context,request))

def ListOnDay(request):
    task_list=Tasks.objects.order_by('-task_Due')[:50]
    template=loader.get_template('polls/ListOnDay.html')
    today =date.today()
    context={'task_list':task_list,'today':today}
    return HttpResponse(template.render(context,request))


def ListOnWeek(request):
    today =date.today()
    start_monday = today - datetime.timedelta(days=today.weekday())
    end_monday = today + datetime.timedelta(days=-today.weekday(), weeks=1)
    #task_list=Tasks.objects.order_by('-task_Due')[:50]
    template=loader.get_template('polls/ListOnWeek.html')
    #task_list=Tasks.objects.filter('date__range=[start_monday, end_monday]')[:50]
    task_list=Tasks.objects.filter(task_Due__range=(start_monday, end_monday))
    context={'task_list':task_list}
    return HttpResponse(template.render(context,request))
    

def ListOnMonth(request):
    task_list=Tasks.objects.order_by('-task_Due')[:50]
    template=loader.get_template('polls/ListOnMonth.html')
    today =date.today()
    context={'task_list':task_list,'today':today}
    return HttpResponse(template.render(context,request))
    
def ListOnYear(request):
    task_list=Tasks.objects.order_by('-task_Due')[:50]
    template=loader.get_template('polls/ListOnYear.html')
    today =date.today()
    context={'task_list':task_list,'today':today}
    return HttpResponse(template.render(context,request))

    
def CrossedDates(request):
    task_list=Tasks.objects.all()[:50]
    template=loader.get_template('polls/CrossedDates.html')
    today =date.today()
    context={'task_list':task_list,'today':today}
    return HttpResponse(template.render(context,request))

polls/templates/polls/AddTask.html
{% load staticfiles %}
<html>
<head>
	<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
          
</head>
<script>
 $('.datepicker').pickadate({
    selectMonths: true,
    selectYears: 15 
  });
  
  $(document).ready(function() {
    $('select').material_select();
  });
        
</script>
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">To DO</a>
      
    </div>
</nav>
<body>
<div class = "container " >
<p> <h4>Add a New Task</h4> </p>
<div class="row">
    <form class="col s12  grey lighten-2" method="post">
	{% csrf_token %}
          {% if errors %}
         <div id="errors">
            <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    </div>
{% endif %}
	{{ form.as_p }}
	<p>Enter in the format YYYY-MM-DD</p>

	<p>  
	  <button class=" col s2 push-s9 btn waves-effect waves-light" type="submit" name="action">Submit
    
  </button>
  </p>
  <br>
  </br>
  
    </form>
  </div>
</div>  
</body>

<footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">ToDo App</h5>
                <p class="grey-text text-lighten-4">An App that lets you list Tasks, set Due date and Sort the tasks to be done on the basis of present day, week, month and year!</p>
              </div>
             
            </div>
          </div>
</footer>
</html>

polls/templates/polls/CrossedDates.html
<html>
<head>
	<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
          
</head>
<script>
$(document).ready(function() {
    $('select').material_select();
  });
</script>

<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">To DO</a>
      
    </div>
</nav>
<body>
<div class = "container">
<h4>DUE DATE OVER</h4>
{% if task_list %}
    <div class="collection">
    {% for tasks in task_list %}
	
		{% load template_filter %}
		
		
		
		{% if tasks.task_Due < today and tasks.task_status != '3' %}
			<a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " deep-orange lighten-4 collection-item">{{ tasks.task_name }} <br> {{ tasks.task_Due }}</a>
		
		{% endif %}

	
    {% endfor %}
	</div>
    
{% else %}
    <p>No Tasks are available.</p>
{% endif %}
</div>
</body>

<footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">ToDo App</h5>
                <p class="grey-text text-lighten-4">An App that lets you list Tasks, set Due date and Sort the tasks to be done on the basis of present day, week, month and year!</p>
              </div>
             
            </div>
          </div>
</footer>
</html>

polls/templates/polls/EditStatus.html
<html>
<head>
	<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
</head>
<script>
 $('.datepicker').pickadate({
    selectMonths: true,
    selectYears: 15 
  });
  
  $(document).ready(function() {
    $('select').material_select();
  });
        
</script>
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">To DO</a>
      
    </div>
</nav>
<body>
<div class = "container">

<p><h4>EDIT TASK STATUS</h4></p>
<div class="row">
		<form class="col s12  grey lighten-2" method="post">
			{% csrf_token %}
			{% if errors %}
			<div id="errors">
				<ul>
					{% for error in errors %}
				<li>{{ error }}</li>
					{% endfor %}
				</ul>
			</div>
            {% endif %}
	
			{{ form.as_p }}
	 <p> 
	  <button class="  col s2 push-s9 btn waves-effect waves-light" type="submit" name="action">Submit
    
  </button>
  </p>
  <br>
</br>
  
    </form>
	</div>
</div>
</body>
<footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">ToDo App</h5>
                <p class="grey-text text-lighten-4">An App that lets you list Tasks, set Due date and Sort the tasks to be done on the basis of present day, week, month and year!</p>
              </div>
             
            </div>
          </div>
</footer>

polls/templates/polls/ListOnDay.html
<html>
<head>
	<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
          
</head>
<script>
$(document).ready(function() {
    $('select').material_select();
  });
</script>

<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">To DO</a>
      
    </div>
</nav>
<body>
<div class = "container">
<h4>Tasks to be Completed by Today</h4>
{% if task_list %}
    
    <div class="collection">
    {% for tasks in task_list %}
	
	{%if tasks.task_Due.day == today.day %}
		{%if tasks.task_status == '1' %}
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " deep-orange lighten-4 collection-item">{{ tasks.task_name }} </a>
		
		
		{%elif tasks.task_status == '2'%}
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " yellow lighten-3 collection-item">{{ tasks.task_name }} </a>
		
		
		{%else%}
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " green lighten-2 collection-item"> {{ tasks.task_name }} </a>
		
		{% endif %}
		
	{% endif %}
	
    
  
	
    {% endfor %}
    </div>
    
{% else %}
    <p>No Tasks are available.</p>
{% endif %}
</div>
</body>

<footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">ToDo App</h5>
                <p class="grey-text text-lighten-4">An App that lets you list Tasks, set Due date and Sort the tasks to be done on the basis of present day, week, month and year!</p>
              </div>
             
            </div>
          </div>
</footer>
</html>

polls/templates/polls/ListOnDueDate.html
<html>
<head>
	<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
          
</head>
<script>
$(document).ready(function() {
    $('select').material_select();
  });
</script>

<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">To DO</a>
      
    </div>
</nav>
<body>
<div class = "container">

<h4>Tasks in the order of Upcoming Due Dates</h4>
{% if task_list %}
    
    {% for tasks in task_list %}
	{%if tasks.task_status != '3'%}
	<div class="collection">
		
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " collection-item">{{ tasks.task_name }} </a>
		
	</div>
	{%endif%}
    {% endfor %}
    
{% else %}
    <p>No Tasks are available.</p>
{% endif %}
</div>
</body>

<footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">ToDo App</h5>
                <p class="grey-text text-lighten-4">An App that lets you list Tasks, set Due date and Sort the tasks to be done on the basis of present day, week, month and year!</p>
              </div>
             
            </div>
          </div>
</footer>
</html>

polls/templates/polls/ListOnMonth.html
<html>
<head>
	<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
          
</head>
<script>
$(document).ready(function() {
    $('select').material_select();
  });
</script>

<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">To DO</a>
      
    </div>
</nav>
<body>
<div class = "container">
<h4>Tasks to be Completed by this Month</h4>
{% if task_list %}

    <div class="collection">
	
    {% for tasks in task_list %}
	
	{%if tasks.task_Due.month == today.month %}
		{%if tasks.task_status == '1' %}
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " deep-orange lighten-4 collection-item">{{ tasks.task_name }} </a>
		
		
		{%elif tasks.task_status == '2'%}
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " yellow lighten-3 collection-item">{{ tasks.task_name }} </a>
		
		
		{%else%}
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " green lighten-2 collection-item"> {{ tasks.task_name }} </a>
		
		{% endif %}
		
	{% endif %}
	
    
  
	
    {% endfor %}
    </div>
{% else %}
    <p>No Tasks are available.</p>
{% endif %}
</div>
</body>

<footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">ToDo App</h5>
                <p class="grey-text text-lighten-4">An App that lets you list Tasks, set Due date and Sort the tasks to be done on the basis of present day, week, month and year!</p>
              </div>
             
            </div>
          </div>
</footer>
</html>

polls/templates/polls/ListOnWeek.html
<html>
<head>
	<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
          
</head>
<script>
$(document).ready(function() {
    $('select').material_select();
  });
</script>

<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">To DO</a>
      
    </div>
</nav>
<body>
<div class = "container">
<h4>Tasks to be Completed by this Week</h4>
{% if task_list %}
    
    <div class="collection">
    {% for tasks in task_list %}
	
	
		{%if tasks.task_status == '1' %}
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " deep-orange lighten-4 collection-item">{{tasks.id}}{{ tasks.task_name }} </a>
		
		
		{%elif tasks.task_status == '2'%}
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " yellow lighten-3 collection-item">{{tasks.id}}{{ tasks.task_name }} </a>
		
		
		{%else%}
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " green lighten-2 collection-item"> {{tasks.id}}{{ tasks.task_name }} </a>
		
		{% endif %}
		
	
	
    
  
	
    {% endfor %}
    </div>
    
{% else %}
    <p>No Tasks are available.</p>
{% endif %}
</div>
</body>

<footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">ToDo App</h5>
                <p class="grey-text text-lighten-4">An App that lets you list Tasks, set Due date and Sort the tasks to be done on the basis of present day, week, month and year!</p>
              </div>
             
            </div>
          </div>
</footer>
</html>

polls/templates/polls/ListOnYear.html
<html>
<head>
	<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
          
</head>
<script>
$(document).ready(function() {
    $('select').material_select();
  });
</script>

<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">To DO</a>
      
    </div>
</nav>
<body>
<div class = "container">
<h4>Tasks to be Completed by this Year</h4>
{% if task_list %}
    
     <div class="collection">
    {% for tasks in task_list %}
	
	{%if tasks.task_Due.year == today.year %}
		{%if tasks.task_status == '1' %}
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " deep-orange lighten-4 collection-item"></br>{{ tasks.task_name }} </a>
		
		
		{%elif tasks.task_status == '2'%}
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " yellow lighten-3 collection-item">{{ tasks.task_name }} </a>
		
		
		{%else%}
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " green lighten-2 collection-item">{{ tasks.task_name }} </a>
		
		{% endif %}
		
	{% endif %}
	
    
  
	
    {% endfor %}
    </div>
    
{% else %}
    <p>No Tasks are available.</p>
{% endif %}
</div>
</body>

<footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">ToDo App</h5>
                <p class="grey-text text-lighten-4">An App that lets you list Tasks, set Due date and Sort the tasks to be done on the basis of present day, week, month and year!</p>
              </div>
             
            </div>
          </div>
</footer>
</html>

polls/templates/polls/TaskInfo.html
<html>
<head>
	<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
</head>
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">To DO</a>
      
    </div>
</nav>
<body>
<div class ="container" >
<h4>TASK DETAILS</h4>
    <ul class="collection">
		
        <li class = "collection-item">  NAME : {{ task.task_name }}</li>
		<li class = "collection-item">  CREATE DATE : {{ task.task_createDate }}</li>
		<li class = "collection-item">  DESCRIPTION : {{ task.task_desc }}</li>
		<li class = "collection-item">  PRIORITY : {{ task.task_priority }}</li>
		<li class = "collection-item">  STATUS : 
		{% if task.task_status == '1'%}
		To Do
		{%elif task.task_status == '2'%}
		Doing
		{%else%}
		Done
		{% endif%}
		
		</li>
		<li class = "collection-item">  DUTE DATE : {{ task.task_Due }}</li>
	</ul>
	</div>
</body>
<footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">ToDo App</h5>
                <p class="grey-text text-lighten-4">An App that lets you list Tasks, set Due date and Sort the tasks to be done on the basis of present day, week, month and year!</p>
              </div>
             
            </div>
          </div>
</footer>
            

polls/templates/polls/index.html
<html>
<head>
	<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
          <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<script>
$(document).ready(function() {
    $('select').material_select();
  });
</script>

<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">To DO</a>
      
    </div>
</nav>
<body>


<div class = "container">


<div class="collection">
<h4> SORT TASKS </h4>    
		<li><a href="{% url 'polls:ListOnDueDate' %}" class="collection-item">LIST BASED ON DUE DATES</a>
<li><a href="{% url 'polls:CrossedDates' %}"  class="collection-item">TASKS THAT HAVE CROSSED DUE DATE</a>
<li><a href="{% url 'polls:ListOnDay' %}"  class="collection-item">LIST BASED ON DAY</a>
<li><a href="{% url 'polls:ListOnWeek' %}"  class="collection-item">LIST BASED ON WEEK</a>
<li><a href="{% url 'polls:ListOnMonth' %}"  class="collection-item">LIST BASED ON MONTH</a>
<li><a href="{% url 'polls:ListOnYear' %}" class="collection-item">LIST BASED ON YEAR</a>
      </div>
            



<!--<li><a href="{% url 'polls:ListOnDueDate' %}">LIST BASED ON DUE DATES</a>
<li><a href="{% url 'polls:CrossedDates' %}">TASKS THAT HAVE CROSSED DUE DATE</a>
<li><a href="{% url 'polls:ListOnDay' %}">LIST BASED ON DAY</a>
<li><a href="{% url 'polls:ListOnWeek' %}">LIST BASED ON WEEK</a>
<li><a href="{% url 'polls:ListOnMonth' %}">LIST BASED ON MONTH</a>
<li><a href="{% url 'polls:ListOnYear' %}">LIST BASED ON YEAR</a>-->
 {% if task_list %}   
    {% for tasks in task_list %}
	<div class="collection">
		{%if tasks.task_status == '1' %}
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " deep-orange lighten-4 collection-item">{{ tasks.task_name }} </a>
		<a href="{% url 'polls:EditStatus' pk=tasks.pk%}" class = "collection-item">Edit Status </a>
		{% endif %}
		{%if tasks.task_status == '2' %}
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = " yellow lighten-3 collection-item">{{ tasks.task_name }} </a>
		<a href="{% url 'polls:EditStatus' pk=tasks.pk %}" class = "collection-item">Edit Status </a>
		{% endif %}
		{%if tasks.task_status == '3' %}
        <a href="{% url 'polls:TaskInfo' tasks.id %}"  class = "  light-green lighten-2 collection-item">{{ tasks.task_name }} </a>
		<a href="{% url 'polls:EditStatus' pk=tasks.pk %}" class = "collection-item">Edit Status </a>
		{% endif %}
	</div>
    {% endfor %}
    
{% else %}
    <p>No Tasks are available.</p>
{% endif %}
<div class = "row">

<div class = "col s3 push-s9">
<h5>ADD A TASK</h5>
</div>

<div class = "col s2 push-s8">
<a href = "{% url 'polls:AddTask' %}" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
</div>

</div>
</div>
</body>

<footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">ToDo App</h5>
                <p class="grey-text text-lighten-4">An App that lets you list Tasks, set Due date and Sort the tasks to be done on the basis of present day, week, month and year!</p>
              </div>
             
            </div>
          </div>
</footer>
</html>